server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。（多server访问地址用于搭建eureka集群环境）
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    
spring:
  application:
    name: eureka-client-demo2